### ISSUE TITLE
Public Release Sprint List; Minimum todo's to release the current indev version to the public. 

### ISSUE THREAD

**Issue by Servius** [Servius/sepcrisistroopsgui#36]
- [x] Include new battlemaps submitted by hwyl
- [x] Include new battlemaps submitted by vLove
- [x] Include Hideouts submitted by hwyl
- [x] Include Hideouts submitted by vLove
- [x] Expanded Separatist Kingdom(add castle and associated villages)
- [ ] Add Deathwatch Culture
- [x] Add Deathwatch Kingdom
- [x] Add Deathwatch Town, Castle, and associated villages
- [ ] Add Arctics republic calvary troop tree
- [ ] Include lightsaber FX and Sound updates by FierceRebel
- [ ] Fix E-5 hold position
- [ ] Update UI Health Hud elements to use our own
- [ ] Update FAQ with notice that battle size must be at least 300 to successfully prebuild shader cache
- [x] Setup directlink download for MyLittleWarband(permission granted by content creator)

**Comment by Servius** [comment]
Deathwatch culture needs mandalorian police outfit to complete, crash being caused by unrecruitable notables
